apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-registry
  template:
    metadata:
      labels:
        app: model-registry
    spec:
      containers:
        - name: registry
          image: model-registry:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
