apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-registry
  template:
    metadata:
      labels:
        app: model-registry
    spec:
      containers:
      - name: model-registry
        image: model-registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: model-registry
spec:
  selector:
    app: model-registry
  ports:
    - port: 8000
      targetPort: 8000
